services:
  web:
    build: .
    volumes:
      - sqlite_data:/app/data
      - staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=django-insecure-tk$^n+0(f9pvd9(s03)0)%$o^m0&so=s0!f)-n)=jptbkwl8e3
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=*
      - DATABASE_PATH=/app/data/db.sqlite3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/app/staticfiles:ro
    depends_on:
      - web

volumes:
  sqlite_data:
  staticfiles:
