# Generated by Django 6.0.5 on 2026-05-21 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=1, unique=True, verbose_name="Nome"),
                ),
            ],
            options={
                "verbose_name": "Grupo",
                "verbose_name_plural": "Grupos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player1_name",
                    models.CharField(max_length=100, verbose_name="Jogador 1"),
                ),
                (
                    "player2_name",
                    models.CharField(max_length=100, verbose_name="Jogador 2"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="tournament.group",
                        verbose_name="Grupo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dupla",
                "verbose_name_plural": "Duplas",
                "ordering": ["group", "pk"],
                "unique_together": {("player1_name", "player2_name", "group")},
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("group", "Fase de grupos"),
                            ("quarterfinal", "Quartas de final"),
                            ("semifinal", "Semifinal"),
                            ("third_place", "Disputa de 3o lugar"),
                            ("final", "Final"),
                            ("fifth_to_eighth", "Disputa de 5o ao 8o"),
                            ("placement_9_14", "Disputa de 9o ao 14o"),
                        ],
                        max_length=20,
                        verbose_name="Fase",
                    ),
                ),
                (
                    "match_number",
                    models.PositiveIntegerField(verbose_name="Numero do jogo"),
                ),
                (
                    "bracket_type",
                    models.CharField(
                        choices=[
                            ("group", "Grupo"),
                            ("main", "Mata-mata principal"),
                            ("placement", "Disputa de posicoes"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de bracket",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("in_progress", "Em andamento"),
                            ("finished", "Finalizada"),
                            ("blocked", "Bloqueada"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "best_of",
                    models.PositiveIntegerField(default=3, verbose_name="Melhor de"),
                ),
                (
                    "source_team_a",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Origem time A",
                    ),
                ),
                (
                    "source_team_b",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Origem time B",
                    ),
                ),
                (
                    "final_position_winner",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Posicao vencedor"
                    ),
                ),
                (
                    "final_position_loser",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Posicao perdedor"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Ordem"),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data planejada"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches",
                        to="tournament.group",
                        verbose_name="Grupo",
                    ),
                ),
                (
                    "team_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_as_team_a",
                        to="tournament.team",
                        verbose_name="Time A",
                    ),
                ),
                (
                    "team_b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_as_team_b",
                        to="tournament.team",
                        verbose_name="Time B",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_won",
                        to="tournament.team",
                        verbose_name="Vencedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partida",
                "verbose_name_plural": "Partidas",
                "ordering": ["sort_order", "match_number"],
                "unique_together": {("match_number", "bracket_type")},
            },
        ),
        migrations.CreateModel(
            name="MatchSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_number", models.PositiveIntegerField(verbose_name="Set")),
                (
                    "team_a_points",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Pontos time A"
                    ),
                ),
                (
                    "team_b_points",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Pontos time B"
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="tournament.match",
                        verbose_name="Partida",
                    ),
                ),
            ],
            options={
                "verbose_name": "Set",
                "verbose_name_plural": "Sets",
                "ordering": ["match", "set_number"],
                "unique_together": {("match", "set_number")},
            },
        ),
    ]
