# Generated by Django 6.0.5 on 2026-05-21 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Double",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "player_1",
                    models.CharField(max_length=100, verbose_name="Jogador 1"),
                ),
                (
                    "player_2",
                    models.CharField(max_length=100, verbose_name="Jogador 2"),
                ),
            ],
            options={
                "verbose_name": "Dupla",
                "verbose_name_plural": "Duplas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=10, unique=True, verbose_name="Nome"),
                ),
                (
                    "doubles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="groups",
                        to="tournament.double",
                        verbose_name="Duplas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo",
                "verbose_name_plural": "Grupos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("grupo", "Grupo"),
                            ("semifinal", "Semifinal"),
                            ("final", "Final"),
                            ("disputa", "Disputa"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("in_progress", "Em andamento"),
                            ("finished", "Finalizada"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "match_number",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Numero do jogo"
                    ),
                ),
                (
                    "source_match_1_is_winner",
                    models.BooleanField(
                        blank=True,
                        help_text="True se dupla 1 vem do vencedor, False se do perdedor",
                        null=True,
                        verbose_name="Dupla 1 e vencedora do jogo de origem",
                    ),
                ),
                (
                    "source_match_2_is_winner",
                    models.BooleanField(
                        blank=True,
                        help_text="True se dupla 2 vem do vencedor, False se do perdedor",
                        null=True,
                        verbose_name="Dupla 2 e vencedora do jogo de origem",
                    ),
                ),
                (
                    "source_double_1_desc",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Descricao origem dupla 1",
                    ),
                ),
                (
                    "source_double_2_desc",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Descricao origem dupla 2",
                    ),
                ),
                (
                    "final_position_winner",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Posicao vencedor"
                    ),
                ),
                (
                    "final_position_loser",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Posicao perdedor"
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Ordem"),
                ),
                (
                    "double_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_as_double_1",
                        to="tournament.double",
                        verbose_name="Dupla 1",
                    ),
                ),
                (
                    "double_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_as_double_2",
                        to="tournament.double",
                        verbose_name="Dupla 2",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches",
                        to="tournament.group",
                        verbose_name="Grupo",
                    ),
                ),
                (
                    "source_match_1",
                    models.ForeignKey(
                        blank=True,
                        help_text="Partida que define a dupla 1 desta partida",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependent_as_double_1",
                        to="tournament.match",
                        verbose_name="Jogo de origem dupla 1",
                    ),
                ),
                (
                    "source_match_2",
                    models.ForeignKey(
                        blank=True,
                        help_text="Partida que define a dupla 2 desta partida",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependent_as_double_2",
                        to="tournament.match",
                        verbose_name="Jogo de origem dupla 2",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_won",
                        to="tournament.double",
                        verbose_name="Vencedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partida",
                "verbose_name_plural": "Partidas",
                "ordering": ["sort_order", "match_number"],
            },
        ),
        migrations.CreateModel(
            name="Set",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_number", models.PositiveIntegerField(verbose_name="Set")),
                (
                    "points_double_1",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Pontos dupla 1"
                    ),
                ),
                (
                    "points_double_2",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Pontos dupla 2"
                    ),
                ),
                (
                    "double_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sets_as_double_1",
                        to="tournament.double",
                        verbose_name="Dupla 1",
                    ),
                ),
                (
                    "double_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sets_as_double_2",
                        to="tournament.double",
                        verbose_name="Dupla 2",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="tournament.match",
                        verbose_name="Partida",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sets_won",
                        to="tournament.double",
                        verbose_name="Vencedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Set",
                "verbose_name_plural": "Sets",
                "ordering": ["match", "set_number"],
                "unique_together": {("match", "set_number")},
            },
        ),
    ]
