# Generated by Django 6.0.5 on 2026-05-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=10, unique=True, verbose_name="Nome"),
        ),
    ]
