# Generated by Django 6.0.5 on 2026-05-21 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0002_alter_group_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="source_match_a",
            field=models.ForeignKey(
                blank=True,
                help_text="Partida que define o time A desta partida",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dependent_as_team_a",
                to="tournament.match",
                verbose_name="Jogo de origem time A",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="source_match_a_is_winner",
            field=models.BooleanField(
                blank=True,
                help_text="True se time A vem do vencedor, False se do perdedor",
                null=True,
                verbose_name="Time A e vencedor do jogo de origem",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="source_match_b",
            field=models.ForeignKey(
                blank=True,
                help_text="Partida que define o time B desta partida",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dependent_as_team_b",
                to="tournament.match",
                verbose_name="Jogo de origem time B",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="source_match_b_is_winner",
            field=models.BooleanField(
                blank=True,
                help_text="True se time B vem do vencedor, False se do perdedor",
                null=True,
                verbose_name="Time B e vencedor do jogo de origem",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="source_team_a",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Descricao origem time A",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="source_team_b",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Descricao origem time B",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("ready", "Pronta"),
                    ("in_progress", "Em andamento"),
                    ("finished", "Finalizada"),
                    ("blocked", "Bloqueada"),
                ],
                default="pending",
                max_length=15,
                verbose_name="Status",
            ),
        ),
    ]
