# Generated by Django 6.0.5 on 2026-05-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tournament",
            "0003_match_source_match_a_match_source_match_a_is_winner_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={
                "ordering": ["team_number"],
                "verbose_name": "Dupla",
                "verbose_name_plural": "Duplas",
            },
        ),
        migrations.AddField(
            model_name="team",
            name="team_number",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Numero da dupla"
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="phase",
            field=models.CharField(
                choices=[
                    ("group", "Fase de grupos"),
                    ("quarterfinal", "Quartas de final"),
                    ("semifinal", "Semifinal"),
                    ("third_place", "Disputa de 3° lugar"),
                    ("final", "Final"),
                    ("fifth_to_eighth", "Disputa de 5° ao 8°"),
                    ("seventh_place", "Disputa de 7° e 8°"),
                    ("fifth_place", "Disputa de 5° e 6°"),
                    ("twelfth_to_fourteenth", "Disputa do 12° ao 14°"),
                    ("ninth_to_eleventh", "Disputa do 9° ao 11°"),
                ],
                max_length=30,
                verbose_name="Fase",
            ),
        ),
    ]
